### ISSUE TITLE
Retirar arquivos do coveralls e codeclimate

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#130]
## Description

Remover arquivos que não deviam entrar na avaliação do codeclimate e do coveralls

## Tasks
- [x] Twitch
- [x] Youtube
- [x] Steam
- [x] IGDB
- [ ] Front

## Acceptance criteria

Ajustes deverão refletir nas métricas de cada uma dessas ferramentas

## How this will benefit the project?
Representação mais confiável das métricas

**Comment by nukdown** [comment]
@felipe72 essa issue já foi finalizada? Pode fechar?
