### ISSUE TITLE
Atualizar documento de arquitetura

### ISSUE THREAD

**Issue by arthurarp** [fga-eps-mds/2018.2-GamesBI#137]
## Description
 Corrigir o modelo arquitetural do projeto no documento de arquitetura.

## Tasks
- [x] doc de arquitetura

## Acceptance criteria
Ajustes deverão estar corretos.

## How this will benefit the project?
Deixar o padrão arquitetural, descrito no documento, em sincronia com o projeto.

**Comment by BRZangado** [comment]
No tópico 4.2 adicionar também uma descrição sobre a YoutubeService

**Comment by BRZangado** [comment]
Adicionar MER do YoutubeService no tópico 5

**Comment by BRZangado** [comment]
Atualizar MER CrossData

**Comment by BRZangado** [comment]
No tópico 3.2, retirar "Padrão MVT"
Adicionar ReactJS

**Comment by BRZangado** [comment]
Diagrama de Pacotes sumiu??

**Comment by BRZangado** [comment]
Tópico 2.1, "Aplicação", A aplicação da API dos microserviços está incompleta

**Comment by BRZangado** [comment]
Refatorar atributos do MER do CrossData
muitos atributos diferentes então com nomes muito parecidos

**Comment by BRZangado** [comment]
Nome do jogo no MER do YoutubeService?
