### ISSUE TITLE
Finalizar todos os tópicos do perfil de comunidade

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#14]
- [x] Description
- [x] README
- [x] Code of conduct
- [x] Contributing
- [x] License
- [x] Issue templates
- [x] Pull request template

**Comment by felipe72** [comment]
Não esqueçam de colocar os arquivos gerados dentro da pasta docs, pra não ficar solto na raiz do projeto

**Comment by BRZangado** [comment]
Adicionar como configurar e rodar o docker no Contributing

**Comment by BRZangado** [comment]
A licença ainda não foi adicionada
