### ISSUE TITLE
US12 Visualizar os jogos para analisar por horas stremadas

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#143]
## Description

Gera um filtro que analise jogos por horas stremadas

## Tasks
- [ ] Criar questão no metabase
- [ ] Importar para o frontend

## Acceptance criteria

Os jogos devem estar listados por horas "stremadas".
## How this will benefit the project?
Conteudo para o produto

**Comment by alanrslima** [comment]
Issue fechada porque foi retirada do back log. Nao sera implementada, portanto recebeu tag invalid e foi fechada
