### ISSUE TITLE
US14 visualizar um indicador para analisar relação entre visualizações e curtidas

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#145]
## Description

Gera um filtro que analise jogos por visualizações e curtidas
## Tasks
- [ ] Criar questão no metabase
- [ ] Importar para o frontend

## Acceptance criteria

Os jogos devem estar listados por horas numero de viewers e likes
## How this will benefit the project?
Conteudo para o produto

**Comment by alanrslima** [comment]
Issue fechada porque foi retirada do back log. Nao sera implementada, portanto recebeu tag invalid
