### ISSUE TITLE
TS10 Guardar histórico de atualizações

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#146]
## Description

Manter um histórico de atualização dos dados importados dos microserviços

## Tasks
- [ ] Remoldar os microserviços

## Acceptance criteria

Testar, atualizar documento de arquitetura

## How this will benefit the project?
Possibilita fazer comparações de jogos pelo tempo

**Comment by felipe72** [comment]
EU acho melhor a gente pegar menos jogos, justamente por causa do tempo de carregar as fixtures, @BRZangado
