### ISSUE TITLE
Atualizar o documento de arquitetura para os desenvolvedores acompanharem a nova demanda de desenvolvimento

### ISSUE THREAD

**Issue by ingrdst** [fga-eps-mds/2018.2-GamesBI#196]
## Descrição
Para a release 2 foram adotadas novas estratégias de desenvolvimento, portanto deverá ser atualizado o documento de arquitetura.

## Tarefas
- [x] Atualizar visão geral da arquitetura. O número de microserviços foram reduzidos, mesclando os importadores em um só.
- [x] Atualizar tecnologias utilizar. Django será substituido pelo flask

## Como isso vai beneficiar o projeto?
Guiar desenvolvedores na nova estratégia escolhida

**Comment by alanrslima** [comment]
Obs: O Django não será substituído pelo flask, eles serão utilizados em conjunto. O Importer service irá usar o Flask, e o crossData o Django
