### ISSUE TITLE
TS25 Endpoint para retornar pesquisas relacionadas

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#204]
## Descrição

Necessitamos de um endpoint usando o verbo POST que terá um parâmetro que será usado como chave para buscar dados de um jogo.

## Tarefas
- [x] tarefa 1
- [x] tarefa 2

**Comment by alanrslima** [comment]
Obs: O endpoint foi criado usando o verbo GET, e não o POST. Pois a sua finalidade é retornar dados utilizando o nome de um jogo ou parte dele

**Comment by BRZangado** [comment]
até hoje a issue não foi pontuada??????????????
