### ISSUE TITLE
TS26 Gerar paleta de cores

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#222]
## Descrição

Eu como desenvolvedor desejo gerar paleta de cores para possibilitar a visualização desse indicador

## Tarefas
- [x] Ler imagens
- [x] Aplicar algoritmo de clusterização 
- [x] Identificar porcentagem de presença de cada paleta

## Critérios de aceitação

Consistir informações sobre a paleta de cores de cada jogo

## Como isso vai beneficiar o projeto?
Possibilita inferir informações e indicadores a partir da paleta de cores

**Comment by nukdown** [comment]
A maior necessidade dessa estória após coletar a paleta de cores de cada jogo é cruzar esses dados com dados de outros jogos que estejam relacionados por algum tipo de filtro, como jogos da mesma categoria, jogos do mesmo ano, etc.

**Comment by arthurarp** [comment]
@alanrslima Essa função já gera uma paleta de cores a partir de qualquer imagem?

**Comment by alanrslima** [comment]
@arthurarp Ela recebe um endereço de imagem hospedada como parâmetro (Ex: http://s2.glbimg.com/C47b1PAM5mEJjLVum8VW7A9M2fc=/0x0:1280x1024/695x556/s.glbimg.com/po/tt2/f/original/2013/01/23/cs1.jpg) e retorna um array de dicionários com os atributos 'r', 'g', 'b', 'hex' que representam cada cor da paleta daquela imagem
