### ISSUE TITLE
Realizar o deploy do Celery e Redis

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#225]
## Descrição

Atualmente o celery só está sendo rodado localmente no ambiente de desenvolvimento

## Tarefas
- [ ] Realizar o deploy do Redis para o heroku
- [ ] Realizar o deploy do Celery worker para o heroku

## Critérios de aceitação

É necessário que o ambiente de homologação e produção dos importadores tenham uma conexão com esses serviços criados

## Como isso vai beneficiar o projeto?
Será realizada a importação de dados periodicamente

**Comment by nukdown** [comment]
Nao atualizou no dia 2/11
