### ISSUE TITLE
Reunião de Elicitação/Validação com o cliente

### ISSUE THREAD

**Issue by augustovilarins** [fga-eps-mds/2018.2-GamesBI#230]
## Descrição

Reunião com o cliente para abordar temas como validação de produto, alinhamento do que está acontecendo no projeto,  discussão sobre o escopo e direcionamento para as duas ultimas sprints.

## Tarefas
- [x] Elaboração de um roteiro de reunião
- [x] Reunir com o cliente
- [x] Gravar a reunião

## Critérios de aceitação

O backlog da R2 precisa ser validado e o entendimento do cliente acerca do projeto tem que estar bem elucidado.

## Como isso vai beneficiar o projeto?

Com o alinhamento do cliente em relação ao que está acontecendo, o cliente também como apoiador, pode dar os direcionamentos necessários para a equipe visando a otimização e conclusão do projeto com eficiência.

**Comment by nukdown** [comment]
qual será o horario da reunião? e local? Vou ver se consigo participar

**Comment by augustovilarins** [comment]
@nukdown A reunião será no LAPPIS ás 15horas.

**Comment by augustovilarins** [comment]
@nukdown Me avisa com antecedência se vai poder participar, que aí eu te dou assign na tarefa também!
