### ISSUE TITLE
API da steamspy com problemas

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#232]
## Descrição

O endpoint que estamos utilizando da API da SteamSpy para resgatarmos todos os jogos da steam está caindo bastante, então seria melhor substitui-lo para um endpoint disponibilizado pela própria steam

## Tarefas
- [ ] Substituir endpoint utilizado para resgatar todos os jogos da steam
- [ ] Realizar uma chamada para o endpoint que retorna dados de somente um jogo da steamspy para ainda termos os dados disponibilizados lá (Esse endpoint parece que continua ok, não é tão instável como o que retorna todos)

## Critérios de aceitação

Os dados deverão ser resgatados à partir do endpoint da steam (https://api.steampowered.com/ISteamApps/GetAppList/v2/)

## Como isso vai beneficiar o projeto?
Garantirá a importação de dados periódicas

**Comment by felipe72** [comment]
O endpoint que estávamos utilizando era: http://steamspy.com/api.php?request=all
e o que iremos utlizar será: https://api.steampowered.com/ISteamApps/GetAppList/v2/

**Comment by alanrslima** [comment]
Foi verificado que a API da steamspy não funciona somente no período noturno. Portanto continuaremos a utilizando porém as requisições de dados serão feitas a tarde.
