### ISSUE TITLE
US16 Visualizar paleta de cores para ajudar no design visual do meu jogo

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#235]
## Titulo da Issue
Eu como usuário desejo visualizar paleta de cores para ajudar no design visual do meu jogo

## Descrição

Demonstrar no front a paleta de cores de todas as screenshots resgatadas dos jogos

## Tarefas
- [x] Criar endpoint para resgatar a paleta de cores do jogo
- [ ] Mostrar a paleta de cores de cada imagem do jogo no front-end

## Como isso vai beneficiar o projeto?
Mais uma informação referente aos jogos

**Comment by felipe72** [comment]
Eu fiz 3 endpoints. São eles:

- /api/?name=NOME_DO_JOGO&partial
  - O parametro partial é opcional. Caso coloque ele, o endpoint irá retornar uma lista de nomes que contenham a string NOME_DO_JOGO no nome dele.
  - Caso contrário ele irá retornar todos os dados desse jogo.

- /api/colors/?genre=NOME_DO_GENRE?color=COLOR
  - Color deverá ser: **r**, **g** ou **b**
  - Esse endpoint irá retornar uma lista de cores ordenada pela cor passada por parametro

- /api/genres/
  - Esse endpoint irá retornar uma lista de todos os gêneros

**Comment by felipe72** [comment]
Exemplo do retorno do endpoint /api/?name=Dota 2
```
{
   "id":1,
   "viewer_count":12450,
   "date":"2018-11-07T23:35:14.695000Z",
   "count_videos":9,
   "count_views":3238176,
   "count_likes":9885,
   "count_dislikes":1564,
   "count_comments":4594,
   "positive_reviews_steam":813055,
   "negative_reviews_steam":120935,
   "owners":150000000,
   "average_forever":26330,
   "average_2weeks":1504,
   "price":0,
   "languages":[
      "Bulgarian",
      "Czech",
      "Danish"
   ],
   "genres":[
      "Action",
      "Free to Play",
      "Strategy"
   ],
   "streams":[
      {
         "id":2,
         "language_stream":"en",
         "started_at":"2018-11-07T20:59:09Z",
         "type":"live",
         "stream_view_count":3185,
         "date":"2018-11-07T23:35:14.708000Z"
      }
   ],
   "screenshots":[
      {
         "id":1,
         "url":"https://steamcdn-a.akamaihd.net/steam/apps/570/ss_86d675fdc73ba10462abb8f5ece7791c5047072c.600x338.jpg?t=1536248487",
         "palettes":[
            {
               "id":1,
               "r":138,
               "g":166,
               "b":82,
               "hex":"#8aa652"
            }
         ]
      }
   ]
}
```
