### ISSUE TITLE
US17 Visualizar paleta de cores de um gênero para ajudar no design visual do meu jogo

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#236]
## Titulo da Issue
Eu como usuário desejo visualizar paleta de cores de um gênero para ajudar no design visual do meu jogo	
## Descrição

Mosrtrar a paleta de cores por gênero
## Tarefas
- [ ] Agrupar paleta de cores dos principais jogos de um genero

## Critérios de aceitação

O usuário deve escolher que tipo de gênero deseja buscar a paleta de cores

## Como isso vai beneficiar o projeto?
Melhora o conteúdo do produto

**Comment by alanrslima** [comment]
Issue fechada porque foi retirada do back log. Nao sera implementada, portanto recebeu tag invalid
