### ISSUE TITLE
Teste unitário no crossdata

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#252]
## Descrição

Aumentar a cobertura de testes no microsserviço.

## Tarefas
- [x] Atingir 90% de cobertura no CrossData.

## Critérios de aceitação

Atingir cobertura de 90% de código testado

## Como isso vai beneficiar o projeto?
Certificar que os métodos e funções estão funcionando corretamente.

**Comment by nukdown** [comment]
Cobertura de 92% de testes, parabéns clan.

**Comment by augustovilarins** [comment]
Eu tô emocionado aqui, todo me tremendo
