### ISSUE TITLE
Resolver impedimento de conexão com a internet na FGA

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#28]
- [x] Ingrid
- [x] Emanoel

**Comment by nukdown** [comment]
https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1748839

**Comment by nukdown** [comment]
- [ ] try downgrade libssl for version 1.0.2j-4
https://launchpad.net/ubuntu/zesty/amd64/libssl1.0.2/1.0.2j-4

**Comment by ingrdst** [comment]
Downgraded wpasupplicant (v2.3) 
Solved connection (WPA-WPA2, Enterprise)

**Comment by ingrdst** [comment]
Files unpacked from terminal:
wpasupplicant_2.3-1+deb8u5_amd64.deb
libssl1.0.0_1.0.1t-1+deb8u8_amd64.deb
libreadline6_6.3-8+b3_amd64.deb

Commands to hold the wpasupplicant version so it doesn't get updated:
(sudo apt-get install aptitude)
sudo aptitude hold wpasupplicant
