### ISSUE TITLE
Criar roadmap para cada uma das àreas

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#32]
## Issue Title
Criar roadmap para cada uma das àreas

## Description

Criar o roadmap para cada uma das áreas de gerenciamento: DevOps, Arquitetura, Engenharia de produto e Scrum Master

## Tasks
- [x] DevOps
- [x] Arquitetura
- [x] Engenharia de produto
- [x] Scrum Master

## Acceptance criteria

Evidências do roadmap criado na wiki do projeto de cada uma das áreas

## How this will benefit the project?
Melhor gerenciamento de cada uma das áreas

**Comment by BRZangado** [comment]
Criei a pasta pros roadmaps mas acho que talvez a gente possa mudar de lugar.
E já coloquei o roadmap da arquitetura pra R1
Começar já já a planejar pra R2

**Comment by BRZangado** [comment]
Sugiro padronizar os roadmaps em questão de design
Se gostaram do meu, façam igual. Se não, a gente pensa em outro jeito

**Comment by BRZangado** [comment]
Fiz no draw.io
o xml que está na pasta é pra abrir o roadmap no draw.io
Se quiserem seguir a msm linha de design abre lá o xml pra fazendo por cima
