### ISSUE TITLE
Elaborar protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by BRZangado** [fga-eps-mds/2018.2-GamesBI#50]
## Description
Protótipo de baixa fidelidade para validação de requisitos funcionais e não funcionais

## Tasks
- [ ] Escrever Requisitos
- [x] Desenhar páginas

## Acceptance criteria
Aceitação do Cliente

## How this will benefit the project?
Conduzir o time de desenvolvimento

**Comment by markinlimac** [comment]
Protótipo criado, se encontra na branch "prototypes", na pasta "prototipos"
