### ISSUE TITLE
Elaborar doc. de visão

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#56]
## Description
Elaborar doc. de visão

## Tópicos a serem abordados (Com textos, imagens, etc
- [x] Introdução
- [x] Posição
- [x] Descrições das Partes Interessadas e Usuários
- [x] Visão Geral do Produto
- [x] Recursos do Produto
- [x] Restrições
- [x] Faixas de Qualidade
- [x] Requisitos do Produto

## Acceptance criteria
* Documento bem formatado
* Informações corretas e atualizadas e validada com o colaborador.

## How this will benefit the project?
O documento de visão captura restrições de design e requisitos de alto nível para que o cliente possa compreender o sistema que será desenvolvido. Seu objetivo é fornecer uma visão ampla do produto que se pretende desenvolver, sem se aprofundar em detalhes.

**Comment by augustovilarins** [comment]
Conversei com o cliente pra levantar o escopo dos tópicos que faltavam

**Comment by augustovilarins** [comment]
Todas as tasks foram finalizadas. @nukdown , vc pode
-[ ] Revisar o documento?

**Comment by augustovilarins** [comment]
Terminei a revisão do documento. Coloquei os tópicos que tem que ser alterados no telegram
