### ISSUE TITLE
Revisar roadmap DevOPS

### ISSUE THREAD

**Issue by victorcmoura** [fga-eps-mds/2018.2-GamesBI#67]
## Description
Seria interessante dar uma revisada no roadmap de DevOPS para ela se adequar melhor ao formato de issues. Assim fica mais simples de mapear o esforço necessário para executar as tarefas.

Esse doc pode ajudá-los a ter uma ideia:
https://github.com/fga-eps-mds/A-Disciplina/blob/master/Devops/roadmap-devops.md

**Comment by nukdown** [comment]
@victorcmoura pode dar outro feedback depois da revisão?

**Comment by victorcmoura** [comment]
Opa, @nukdown. Excelente definição das políticas, certamente vai ajudá-los a organizar melhor o trabalho e vai evitar diversos problemas. Ainda assim, acredito que ainda ta faltando colocar em formato de issues mesmo, pra vocês terem uma noção do trabalho. Ter as coisas em formato de issue vai ajudá-los em como realmente implementar as partes técnicas do pipeline. Vocês inclusive já criaram algumas das issues que eu pretendia enxergar no roadmap:

- https://github.com/fga-eps-mds/2018.2-GamesBI/issues/6
- https://github.com/fga-eps-mds/2018.2-GamesBI/issues/7
- https://github.com/fga-eps-mds/2018.2-GamesBI/issues/8

A ideia é continuar fazendo as issues parecidas com essas. Eventualmente vocês vão implementar deploy contínuo e certamente vão existir coisas pra adicionar no roadmap. Ter as issues mapeadas la no doc vai ser uma boas ajuda.

Inclusive, pode adicionar essas issues la pra ficar de exemplo pra quando vocês completarem ;D Se ainda tiverem alguma dúvida, podem me procurar novamente que a gente conversa, sem problemas.
