### ISSUE TITLE
TS05 criar models para a Youtube API

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#83]
## Tasks
- [x] Identificar arquivos que serão consumidos
- [ ] Modelar banco

## Acceptance criteria

Os dados coletados devem ser relevantes

## How this will benefit the project?
Modelará o banco de dados

**Comment by nukdown** [comment]
Os endpoints e os paremetros que vamos usar no service do youtube, alguns dados já da para modelar, mas tem um que retorna graficos a partir da categorias
https://developers.google.com/youtube/v3/docs/videos/list#chart
Usando o "search-list"  dá para obter resultados de uma busca, e depois ver as estatistica de cada video dos resultados. 
https://stackoverflow.com/questions/26199933/youtube-api-3-0-search-videos-and-get-video-statistics-at-single-request

**Comment by lmmLucasMachado** [comment]
Tava vendo api do youtube e ainda não consegui indetificar quais seriam os dados corretos que vamos modelar. mas vi alguns dados que podemos utilizar, com base nesses dados vou criar uma model para ele.
