### ISSUE TITLE
Integrar issues no telegram

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#94]
## Description

Integrar comentarios das issues no telegram

## Tasks
- [x] Configurar bot no telegram

## Acceptance criteria

O bot deve avisar a respeito de qualquer alteração que aconteça nas issues

## How this will benefit the project?
Melhorar comunicação interna da equipe

**Comment by fepas** [comment]
@nukdown lindíssima configurou tudo

**Comment by augustovilarins** [comment]
@nukdown Obrigado pela ajuda na configuração do bot ! @imfepas
