### ISSUE TITLE
US11 Visualizar a homepage

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#96]
## Description

Solidificar o protótipo

## Tasks
- [ ] Criar pagina estática

## Acceptance criteria

Seguir o modelo do prototipo de alta fidelidade
Desenvolver em javascript

## How this will benefit the project?
Melhorar experiência do usuário.

**Comment by Andre-Eduardo** [comment]
Um material bem explicativo e que pode ajudar no desenvolvimento da homepage utilizando React: https://blog.coderockr.com/iniciando-com-react-parte-1-a79d74fe8f8c
